logging:
   level:
      io.github.jtsato.bookstore: debug
      org.springframework.web: warn
      org.apache.dubbo: DEBUG
      io.swagger.models.parameters.AbstractSerializableParameter: error


armeria:
   ports:
      - port: 8080
        protocols:
           - http


dubbo:
   application:
      name: demo-provider # 应用名称
   registry:
      address: zookeeper://127.0.0.1:2181
   protocol:
      name: dubbo
      port: 20880 # Dubbo 协议端口
